<h2>Registrace</h2>
<hr>
<form method="post" name="registration" onsubmit="return validateForm()">

        <label for="username"><strong>Uživatelské jméno</strong></label><br />
        <input type="text" id="username" class="form-control" name="username" /><br />

        <label for="email"><strong>Emailová adresa</strong></label><br />
        <input type="email" id="email" class="form-control" name="email" /><br />

        <label for="password"><strong>Heslo</strong></label><br />
        <input type="password" id="password" class="form-control" name="password" /><br />

        <label for="password_again"><strong>Heslo znovu</strong></label><br />
        <input type="password" id="password_again" class="form-control" name="password_again" /><br /><br />

        <input type="submit" class="btn btn-default" role="button" value="Registrovat" /><br /><br />
</form>

<script>
function validateForm() {
  var name = document.forms["registration"]["username"].value;
  if (name == "") {
    alert("Jméno musí být vyplněno");
    return false;
  }
}
</script>